package com.brucexu.springBootBackend.entity;

import jakarta.persistence.*;

/**
 * Represents a file upload stored in the system.
 *
 * Each upload corresponds to a single object in S3 and tracks
 * its processing status throughout the pipeline.
 */
@Entity
public class Upload {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long uploadId;

    private String userId;
    private String s3Key;
    @Enumerated(EnumType.STRING)
    private UploadStatus status;

    /**
     * Creates a new upload record.
     *
     * <p>The creation timestamp is automatically initialized to the current
     * time. The primary key is generated by JPA when the entity is persisted.</p>
     *
     * @param userId the ID of the user who owns the upload; may be {@code null}
     *               if the user has not yet been associated with the upload
     * @param s3Key the unique S3 object key for the uploaded file
     * @param status the initial processing status of the upload
     */
    public Upload(String userId, String s3Key, UploadStatus status) {
        this.userId = userId;
        this.s3Key = s3Key;
        this.status = status;
    }

    /**
     * Updates the current processing status of the upload.
     *
     * @param newStatus the new upload status
     */
    public void setStatus(UploadStatus newStatus){
        this.status = newStatus;
    }

    /**
     * Retrieves the uploadID upon insertion.
     *
     * @return uploadId
     */
    public Long getUploadId() {
        return uploadId;
    }

    /**
     * Retrieves the uploadID upon insertion.
     *
     * @return uploadId
     */
    public String getS3Key() {
        return s3Key;
    }

    /**
     * Required by JPA for entity instantiation.
     */
    protected Upload() {
    }
}
